
sudo: false
language: ruby
env:
  - ES_IMAGE=elasticsearch:1
  - ES_IMAGE=plainpicture/elasticsearch:2.4.1_delete-by-query
  - ES_IMAGE=elasticsearch:5.4
  - ES_IMAGE=docker.elastic.co/elasticsearch/elasticsearch:6.7.0
  - ES_IMAGE=docker.elastic.co/elasticsearch/elasticsearch:7.0.0
  - ES_IMAGE=docker.elastic.co/elasticsearch/elasticsearch:7.4.0
rvm:
  - ruby-2.6.2
  - ruby-2.7.1
before_install:
  - docker-compose up -d
  - sleep 10
install:
  - travis_retry bundle install
script: rspec

