
dist: trusty

rvm:
  - 2.1.10
  - 2.2.5
  - 2.3.1

jdk:
  - openjdk8

install:
  - travis_retry bundle install
  - curl -s https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-5.4.0.tar.gz | tar xz -C /tmp
  - /tmp/elasticsearch-5.4.0/bin/elasticsearch -d

before_script:
  - sleep 15

script:
  - bundle exec rake test

sudo: false

