
rvm:
  - 2.1.10
  - 2.2.5
  - 2.3.1

jdk:
  - openjdk7

install:
  - travis_retry bundle install
  - curl -s https://download.elastic.co/elasticsearch/release/org/elasticsearch/distribution/tar/elasticsearch/2.4.1/elasticsearch-2.4.1.tar.gz | tar xz -C /tmp
  - /tmp/elasticsearch-2.4.1/bin/plugin install delete-by-query
  - /tmp/elasticsearch-2.4.1/bin/elasticsearch -d

before_script:
  - sleep 10

script:
  - bundle exec rake test

sudo: false

